import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Work from "../components/Work";
// import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kyle Mayer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <Work />
      <Footer />
    </div>
  );
}
